"""Code-owned operations around Galley's retained editorial readers.

No commands or completion claims are generated by a model here. The selected
recipe, two verification passes, and final Astra clearance remain explicit.
"""
from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping
from pathlib import Path
from typing import Callable

from docproof.utils.files import write_atomic

PHASES = frozenset({"approve", "audit", "verify", "settle"})
POLICY_ID = "mechanical-verification-v1"
PASS_IDS = ("primary", "type-compare")
READER_MODELS = {"primary": "claude-opus-5", "type-compare": "claude-fable-5-1"}


def _json(path):
    return json.loads(Path(path).read_text("utf-8"))


class EnginePhaseError(ValueError):
    pass


def _profile_comment_budget(value) -> int:
    """Extract a stated ceiling without rounding or removing its constraint."""
    if isinstance(value, Mapping):
        value = value.get("ceiling")
    if type(value) is float and math.isfinite(value) and value.is_integer():
        value = int(value)
    # The approval manifest treats zero as no ceiling, so it cannot be passed
    # through as a valid constraint. Bool is also not an editorial count.
    if type(value) is not int or value <= 0:
        raise EnginePhaseError(
            "profile.json comment_budget must be a positive integer or an "
            "object with a positive integer ceiling")
    return value


def review_action(*, coverage_complete: bool, open_ids: set[str],
                  prior_ids: set[str], rounds: int, max_rounds: int,
                  affected_paragraphs: int, reviewed_paragraphs: int) -> str:
    """Choose work, never issue the final editorial verdict.

    A low count is not a clean certificate. Persisted IDs distinguish repeated
    noise from progress. Astra independently rules on substantive leftovers.
    """
    if not coverage_complete:
        return "blocked"
    if not open_ids:
        return "final_review"
    if rounds >= max_rounds or (rounds and open_ids == prior_ids):
        return "final_review_with_residuals"
    if reviewed_paragraphs and affected_paragraphs / reviewed_paragraphs >= .20:
        return "broad_repair"
    return "local_repair"


class EnginePhases:
    def __init__(self, driver, execute: Callable):
        self.driver = driver
        self.execute = execute
        self.ws = driver.workspace.resolve()
        self.directory = self.ws / "runs" / "driver" / "engine"
        self.directory.mkdir(parents=True, exist_ok=True)

    def _config(self):
        path = self.ws / "runs" / "mech.yaml"
        approval = self.ws / "approval.json"
        if approval.exists():
            path = Path(_json(approval)["config_path"])
            if not path.is_absolute():
                path = self.ws / path
        path = path.resolve()
        path.relative_to(self.ws)
        if not path.is_file():
            raise EnginePhaseError("The approved manuscript configuration is missing")
        return path

    def _advance(self, state):
        from galley.state_machine import RunStateMachine
        from galley.manifest import sha256_file
        path = self.ws / "state.json"
        machine = RunStateMachine.load(path)
        approval = _json(self.ws / "approval.json")
        if not machine.reached(state):
            machine.advance(state, by="galley code execution",
                            source_sha256=sha256_file(self.driver.book),
                            config_sha256=approval["config_sha256"])
            machine.save(path)

    def _command(self, phase, name, arguments, outputs, *, acceptable=(0,), validate=None):
        from galley.driver import PhaseSpec
        from galley.manifest import sha256_file
        context = Path(arguments[arguments.index("--context") + 1]) if "--context" in arguments else None
        run = self.driver._final_run()
        identity = {"source": sha256_file(self.driver.book),
                    "config": sha256_file(self._config()), "arguments": arguments,
                    "context": sha256_file(context) if context else None}
        fingerprint = hashlib.sha256(json.dumps(identity, sort_keys=True).encode()).hexdigest()
        from galley.verify import build_fingerprints
        run = self.driver._final_run()
        build = build_fingerprints(run) if run else {}
        if run and (run / "findings.json").is_file():
            build["findings_sha256"] = sha256_file(run / "findings.json")
        receipt = self.directory / f"{name}.json"
        if receipt.exists():
            saved = _json(receipt)
            if saved["fingerprint"] != fingerprint:
                raise EnginePhaseError(f"{name}: inputs differ from the saved operation")
            if saved.get("status") == "running":
                raise EnginePhaseError(f"{name}: interrupted operation needs receipt reconciliation")
            if saved.get("status") == "completed":
                if (saved.get("output_build") == build and
                    all(p.is_file() and saved["outputs"].get(str(p)) == sha256_file(p)
                        for p in outputs) and (validate is None or validate())):
                    return
                # Later valid phases may supersede these files. The phase
                # caller must choose a new operation name for a fresh read.
                raise EnginePhaseError(f"{name}: completed output has changed; reconcile the saved operation")
        argv = ["docproof", "galley", *arguments]
        log_path = self.directory / f"{name}.log"
        write_atomic(receipt, json.dumps({"fingerprint": fingerprint,
            "status": "running", "arguments": arguments, "input_build": build}, indent=2))
        env = self.driver._resource_env(phase, self.driver._engine_env)
        env["DOCPROOF_RESOURCE_PARENT_OPERATION"] = name
        spec = PhaseSpec(phase=phase, prompt="", workspace=self.ws,
                         log_path=log_path, argv=argv, env=env, max_turns=0,
                         timeout_s=self.driver.timeout_for(phase))
        result = self.execute(spec)
        if result.returncode not in acceptable or result.limit:
            write_atomic(receipt, json.dumps({"fingerprint": fingerprint,
                "status": "failed", "arguments": arguments, "input_build": build,
                "log": str(getattr(result, "log_path", log_path))}, indent=2))
            raise EnginePhaseError(f"{name}: {result.limit or result.returncode}: {result.tail}")
        if not all(p.is_file() for p in outputs) or (validate is not None and not validate()):
            write_atomic(receipt, json.dumps({"fingerprint": fingerprint,
                "status": "incomplete", "arguments": arguments, "input_build": build}, indent=2))
            raise EnginePhaseError(f"{name}: command ended without complete required evidence")
        output_build = build_fingerprints(run) if run else {}
        if run and (run / "findings.json").is_file():
            output_build["findings_sha256"] = sha256_file(run / "findings.json")
        write_atomic(receipt, json.dumps({"fingerprint": fingerprint,
            "status": "completed", "arguments": arguments,
            "input_build": build, "output_build": output_build,
            "outputs": {str(p): sha256_file(p) for p in outputs}}, indent=2))

    def _context(self, pass_id):
        parts = []
        for name in ("voice-notes.md", "VOICE.md", "VOICE_NOTES.md", "DECISIONS.md",
                     "intent-zones.json"):
            path = self.ws / name
            if path.is_file():
                parts.append(f"Book evidence from {name}:\n{path.read_text('utf-8')}")
        if pass_id == "type-compare":
            parts.append("Independent slow comparison pass: attend to omissions, accidental "
                "duplication, wrong-word sense, and the exact words in each accepted paragraph. "
                "Investigate source context. Do not rely on prior reviewers' assurances. "
                "Silently reconstruct each paragraph as a minimal proofread and compare "
                "the exact wording before returning discrepancies. Do not rewrite for style. "
                "Return anchored findings under the verification schema, preserving author intent.")
        path = self.directory / f"{pass_id}-context.txt"
        text = "\n\n".join(parts)
        if not path.exists() or path.read_text('utf-8') != text:
            write_atomic(path, text)
        return path

    def approve(self):
        approval = self.ws / "approval.json"
        if not approval.exists():
            args = ["approve", str(self.driver.book), "--config", str(self._config()),
                    "--budget", str(self.driver.budget_usd), "--out", str(approval),
                    "--mechanical-only", "--note", "Approved by the code-owned plan gate"]
            profile = self.ws / "profile.json"
            if profile.is_file():
                profile_data = _json(profile)
                if not isinstance(profile_data, Mapping):
                    raise EnginePhaseError("profile.json must be an object")
                if "comment_budget" in profile_data:
                    args += ["--comment-budget",
                             str(_profile_comment_budget(profile_data["comment_budget"]))]
            self._command("approve", "approve", args, [approval])
        else:
            from galley.manifest import sha256_file, config_hash
            from docproof.__main__ import _effective_cfg
            from types import SimpleNamespace
            saved = _json(approval)
            if saved.get("source_sha256") != sha256_file(self.driver.book):
                raise EnginePhaseError("Approval belongs to a different manuscript")
            if saved.get("config_sha256") != config_hash(_effective_cfg(SimpleNamespace(
                    config=str(self._config()), stage=None, genre=None))):
                raise EnginePhaseError("Approved configuration has changed")
        self._advance("plan_approved")

    def audit(self):
        run = self.driver._final_run()
        if run is None:
            raise EnginePhaseError("Audit needs completed detector findings")
        self._command("audit", "audit", ["audit", str(run), "--source",
            str(self.driver.book), "--config", str(self._config()),
            "--approval", str(self.ws / "approval.json"), "--out", str(self.ws / "runs")],
            [self.ws / "runs" / "audit.json"])
        self._advance("audited")

    def _coverage(self, run, *, require_full_passes=False, only_pass=None):
        from galley.verify import build_fingerprints, applied_edits, accepted_text
        fp = build_fingerprints(run)
        if not fp:
            return False
        dirs = [(run, "primary")]
        if require_full_passes:
            dirs.append((run / "verification" / "type-compare", "type-compare"))
        if only_pass:
            dirs = [(run if only_pass == "primary" else run / "verification" / only_pass, only_pass)]
        for directory, pass_id in dirs:
            if require_full_passes:
                from galley.verify import validate_complete_pass
                from docproof.providers.subagent import SubagentProvider, resolve_model
                from docproof.__main__ import _effective_cfg, _verification_policy
                from types import SimpleNamespace
                model = READER_MODELS[pass_id]
                cfg = _effective_cfg(SimpleNamespace(config=str(self._config()), stage=None, genre=None))
                provider = SubagentProvider(model=model, effort=cfg.api.effort)
                if not validate_complete_pass(run, directory, provider,
                        f"subagent:{resolve_model(model)}", context=self._context(pass_id).read_text("utf-8"),
                        engine="subagent", pass_id=pass_id, required_pass_ids=PASS_IDS,
                        policy_id=POLICY_ID, config_sha256=_verification_policy(SimpleNamespace(), cfg)["config_sha256"]):
                    return False
            for filename, count_key, count, gate in (
                    ("change_verify.json", "applied_edits", len(applied_edits(run)), "changes"),
                    ("finished_walk.json", "paragraphs", sum(bool(t.strip()) for t in accepted_text(run).values()), "walk")):
                path = directory / filename
                if not path.is_file():
                    return False
                payload = _json(path)
                if (payload.get("ran") is not True or payload.get(count_key) != count
                        or any(payload.get(k) for k in ("unread_batches", "unread_paragraphs", "unverified_paragraphs"))
                        or any(payload.get(k) != fp[k] for k in
                               ("build_sha256", "accepted_sha256", "paragraph_sha256", "source_sha256"))):
                    return False
                if require_full_passes:
                    proof = payload.get("verification_provenance") or {}
                    identity = proof.get("identity") or {}
                    policy = identity.get("policy") or {}
                    if (proof.get("complete") is not True or identity.get("gate") != gate
                            or identity.get("document_sha256") != fp["build_sha256"]
                            or policy != {"id": POLICY_ID, "pass_id": pass_id,
                                          "required_pass_ids": list(PASS_IDS)}):
                        return False
        return True

    def verify(self, *, cycle=0):
        run = self.driver._final_run()
        if run is None:
            raise EnginePhaseError("Verification needs a completed manuscript")
        for pass_id, model in READER_MODELS.items():
            out = run if pass_id == "primary" else run / "verification" / pass_id
            args = ["verify", str(run), "--config", str(self._config()),
                    "--engine", "subagent", "--model", model,
                    "--verification-pass", pass_id, "--verification-policy", POLICY_ID,
                    "--required-verification-passes", ",".join(PASS_IDS),
                    "--context", str(self._context(pass_id)), "--out", str(out)]
            self._command("verify", f"verify-{cycle}-{pass_id}", args,
                          [out / "change_verify.json", out / "finished_walk.json"],
                          acceptable=(0, 1), validate=lambda p=pass_id:
                          self._coverage(run, require_full_passes=True, only_pass=p))
        if not self._coverage(run, require_full_passes=True):
            raise EnginePhaseError("Both independent reads must prove complete coverage of this manuscript")
        import shutil
        from galley.manifest import sha256_file
        artifacts = {}
        archive = self.directory / "coverage" / str(cycle)
        for pass_id in PASS_IDS:
            source = run if pass_id == "primary" else run / "verification" / pass_id
            for name in ("change_verify.json", "finished_walk.json"):
                target = archive / pass_id / name
                target.parent.mkdir(parents=True, exist_ok=True)
                if target.exists() and sha256_file(target) != sha256_file(source / name):
                    raise EnginePhaseError("Original full-read receipt has changed")
                if not target.exists():
                    shutil.copyfile(source / name, target)
                artifacts[str(target.relative_to(self.directory))] = sha256_file(target)
        write_atomic(self.directory / "initial-coverage.json", json.dumps({
            "schema_version": 1, "cycle": cycle,
            "source": sha256_file(self.driver.book), "config": sha256_file(self._config()),
            "run": str(run.resolve()), "pass_ids": list(PASS_IDS), "artifacts": artifacts,
            "contexts": {p: sha256_file(self._context(p)) for p in PASS_IDS},
        }, indent=2))

    def _initial_coverage_saved(self, run):
        from galley.manifest import sha256_file
        path = self.directory / "initial-coverage.json"
        if not path.is_file():
            return False
        data = _json(path)
        if (data.get("source") != sha256_file(self.driver.book)
                or data.get("config") != sha256_file(self._config())
                or data.get("run") != str(run.resolve()) or data.get("pass_ids") != list(PASS_IDS)
                or len(data.get("artifacts", {})) != 4
                or data.get("contexts") != {p: sha256_file(self._context(p)) for p in PASS_IDS}):
            return False
        for relative, digest in data["artifacts"].items():
            target = (self.directory / relative).resolve()
            if not target.is_relative_to((self.directory / "coverage").resolve()):
                return False
            if not target.is_file() or sha256_file(target) != digest:
                return False
        return True

    def settle(self):
        from galley.settle import open_items
        from galley.verify import accepted_text, build_fingerprints
        run = self.driver._final_run()
        if run is None:
            raise EnginePhaseError("Settlement needs a completed manuscript")
        state_path = self.directory / "review-loop.json"
        from galley.manifest import sha256_file
        identity = {"source": sha256_file(self.driver.book), "run": str(run.resolve()),
                    "config": sha256_file(self._config())}
        state = (_json(state_path) if state_path.exists() else
                 {"schema_version": 1, "identity": identity,
                  "rounds": 0, "prior_ids": [], "history": []})
        if state.get("identity") != identity:
            raise EnginePhaseError("Review loop belongs to different inputs")
        if not 1 <= self.driver.review_rounds <= 2:
            raise EnginePhaseError("Review requires one or two repair rounds")
        max_rounds = min(state.get("max_rounds", self.driver.review_rounds), self.driver.review_rounds)
        state["max_rounds"] = max_rounds
        if state.get("pending_verify_cycle") is not None:
            self.verify(cycle=state["pending_verify_cycle"])
            state.pop("pending_verify_cycle")
            write_atomic(state_path, json.dumps(state, indent=2))
        if not self._initial_coverage_saved(run):
            raise EnginePhaseError("Original two-pass reading receipts are missing or changed")
        if state["rounds"] == 0 and not self._coverage(run, require_full_passes=True):
            raise EnginePhaseError("Both independent reads must complete before settlement")
        while True:
            items = open_items(run)
            ids = {r.id for r in items}
            coverage = self._coverage(run)
            action = review_action(coverage_complete=coverage, open_ids=ids,
                prior_ids=set(state["prior_ids"]), rounds=state["rounds"],
                max_rounds=max_rounds,
                affected_paragraphs=len({r.para_id for r in items}),
                reviewed_paragraphs=len(accepted_text(run)))
            state["history"].append({"round": state["rounds"], "action": action,
                "open_ids": sorted(ids), "fingerprints": build_fingerprints(run)})
            write_atomic(state_path, json.dumps(state, indent=2))
            if action == "blocked":
                raise EnginePhaseError("Required reading evidence is missing")
            if action.startswith("final_review") and (run / "settlement.json").is_file():
                break
            if state["rounds"] >= max_rounds:
                raise EnginePhaseError("Repair budget exhausted with missing settlement evidence")
            # Even a clean read needs a real settlement report; this executes
            # the no-open-items closeout without buying another full read.
            state["prior_ids"] = sorted(ids)
            index = state["rounds"] + 1
            args = ["settle", str(run), "--source", str(self.driver.book),
                    "--config", str(self._config()), "--approval", str(self.ws / "approval.json"),
                    "--engine", "subagent", "--model", "claude-opus-5",
                    "--rounds", "1", "--max-turns", str(self.driver.review_calls),
                    "--mechanical-only", "--verification-pass", "primary",
                    "--verification-policy", POLICY_ID,
                    "--required-verification-passes", ",".join(PASS_IDS),
                    "--context", str(self._context("primary"))]
            self._command("settle", f"settle-{index}", args,
                          [run / "settlement.json"], acceptable=(0, 1))
            state["rounds"] = index
            write_atomic(state_path, json.dumps(state, indent=2))
            if action.startswith("final_review"):
                break
            if action == "broad_repair" and index < max_rounds:
                state["pending_verify_cycle"] = index
                write_atomic(state_path, json.dumps(state, indent=2))
                self.verify(cycle=index)
                state.pop("pending_verify_cycle")
                write_atomic(state_path, json.dumps(state, indent=2))
        if not self._coverage(run):
            raise EnginePhaseError("Repaired manuscript still has unread or stale evidence")
        self._advance("settled")

    def run(self, phase):
        if phase not in PHASES:
            raise EnginePhaseError(f"Unsupported code phase {phase}")
        getattr(self, phase)()
